### ISSUE TITLE
[Bug]:Ihavenoideawhy

### ISSUE THREAD

**Issue by SomeRandomSloth** [Mrbysco/DailyDad-Server#3]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

0.15.11

### Minecraft version

1.21

### Mod version

2.0.0

### Java version

Java 21

### Issue Description

Whenever I open a single-player world it crashes, as well it does not show a dad joke when I join a server

### Additional Information

[15:19:23] [Render thread/ERROR]: Mixin apply for mod dailydad_server failed dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server -> net.minecraft.class_3324: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server->@Inject::respawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/class_3222;ZLnet/minecraft/class_1297$class_5529;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server -> Apply Injections ->  -> Inject -> dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server->@Inject::respawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server->@Inject::respawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/class_3222;ZLnet/minecraft/class_1297$class_5529;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server -> Apply Injections ->  -> Inject -> dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server->@Inject::respawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:564) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_310.method_29603(class_310.java:2153) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2153) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57773(class_7196.java:410) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57776(class_7196.java:405) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57777(class_7196.java:372) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2223) ~[?:?]
	at net.minecraft.class_7196.method_57787(class_7196.java:370) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57790(class_7196.java:351) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_54617(class_7196.java:203) ~[client-intermediary.jar:?]
	at net.minecraft.class_405.method_19793(class_405.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) [lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1310) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Don't do that.
Time: 2024-06-15 15:19:23
Description: Starting integrated server
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_310.method_29603(class_310.java:2153)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:288)
	at net.minecraft.class_310.method_29610(class_310.java:2153)
	at net.minecraft.class_7196.method_57773(class_7196.java:410)
	at net.minecraft.class_7196.method_57776(class_7196.java:405)
	at net.minecraft.class_7196.method_57777(class_7196.java:372)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2223)
	at net.minecraft.class_7196.method_57787(class_7196.java:370)
	at net.minecraft.class_7196.method_57790(class_7196.java:351)
	at net.minecraft.class_7196.method_54617(class_7196.java:203)
	at net.minecraft.class_405.method_19793(class_405.java:35)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
	at net.minecraft.class_310.method_1523(class_310.java:1310)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 43 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server] from phase [DEFAULT] in config [dailydad_server.fabric.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 46 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server->@Inject::respawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/class_3222;ZLnet/minecraft/class_1297$class_5529;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server -> Apply Injections ->  -> Inject -> dailydad_server.fabric.mixins.json:PlayerListMixin from mod dailydad_server->@Inject::respawn(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:564)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 46 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_310.method_29603(class_310.java:2153)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:288)
	at net.minecraft.class_310.method_29610(class_310.java:2153)
	at net.minecraft.class_7196.method_57773(class_7196.java:410)
	at net.minecraft.class_7196.method_57776(class_7196.java:405)
	at net.minecraft.class_7196.method_57777(class_7196.java:372)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2223)
	at net.minecraft.class_7196.method_57787(class_7196.java:370)
	at net.minecraft.class_7196.method_57790(class_7196.java:351)
	at net.minecraft.class_7196.method_54617(class_7196.java:203)
	at net.minecraft.class_405.method_19793(class_405.java:35)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)

**Comment by Mrbysco** [comment]
Whoops that one slipped through. Although Daily Dad server is a server-side mod. For client side dad jokes install [Daily Dad](https://www.curseforge.com/minecraft/mc-mods/daily-dad)

**Comment by Mrbysco** [comment]
A new build is being uploaded that fixes this problem
